apiVersion: v2
appVersion: v0.6.4
description: Sub-second search & analytics engine on cloud storage.
home: https://quickwit.io/
icon: https://avatars.githubusercontent.com/u/98504233?s=200&v=4
keywords:
- quickwit
- search
- analytics
- tracing
- logs
maintainers:
- email: hello@quickwit.io
  name: Quickwit
- email: mkhpalm@gmail.com
  name: mkhpalm
name: quickwit
sources:
- https://github.com/quickwit-oss/quickwit/
type: application
version: 0.5.5
